development:
  host: localhost
  port: 6379
  password: 
  database: 1

test:
  host: localhost
  port: 6379
  password: 
  database: 2

production:
  host: 123.123.123.123
  port: 6380
  password: secret
  database: 5