source 'https://rubygems.org'

# Specify your gem's dependencies in scales-worker.gemspec
gemspec

gem "scales-core", :path => "../scales-core"

# Load the dependencies of the rails app
eval(IO.read(File.expand_path("../spec/fixtures/app/Gemfile", __FILE__)), binding)